export type ContextItemType = "snippet" | "chat" | "note" | "link";

export type ContextItem = {
  type: ContextItemType;
  title: string;
  url?: string;
  desc: string;
  ctx?: string;
  body?: string; // for notes
  code?: string; // for snippets
  folder?: string;
  tags: string[];
  fav?: boolean;
  archived?: boolean;
  savedAt: string; // ISO date string
  // meta: {
  //   author?: string;
  //   len: string; // e.g., "5 min read", "12 lines", "Repository"
  // };
  // attach?: { name: string; kind: "image" | "pdf"; size: string }[];
};

export const contextItems: ContextItem[] = [
  {
    type: "link",
    title: "Server Components",
    url: "https://react.dev/reference/rsc/server-components",
    desc: "Reference for React Server Components: what runs on the server, how they compose with Client Components, and how async components work.",
    ctx: "The clearest explanation of the server/client boundary I have found. Re-read the async components section before we migrate the dashboard routes, because it changes where data fetching lives.",
    folder: "frontend",
    tags: ["react", "nextjs", "docs"],
    fav: true,
    savedAt: "2026-01-01",
    // meta: { author: "React team", len: "14 min read" },
    // attach: [
    //   { name: "rsc-boundary-diagram.png", kind: "image", size: "184 KB" },
    // ],
  },
  {
    type: "link",
    title: "Caching in Next.js",
    url: "https://nextjs.org/docs/app/guides/caching",
    desc: "Overview of the caching layers in the App Router: request memoization, data cache, full route cache and router cache, and how each one is invalidated.",
    ctx: "Keep this open when debugging stale data after revalidatePath. The table showing which cache each API touches is the useful part.",
    folder: "frontend",
    tags: ["nextjs", "caching", "docs"],
    fav: true,
    savedAt: "2026-01-02",
    // meta: { author: "Vercel", len: "18 min read" },
  },
  {
    type: "link",
    title: "Connection pool (Prisma ORM)",
    url: "https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool",
    desc: "How Prisma Client manages its connection pool, how to size it, and what changes in serverless environments.",
    ctx: "Lambda cold starts were exhausting Postgres connections. The fix was connection_limit=1 per function plus PgBouncer in transaction mode. Ticket PLAT-482.",
    folder: "data",
    tags: ["prisma", "postgres", "performance"],
    savedAt: "2026-01-03",
    // meta: { author: "Prisma", len: "9 min read" },
    // attach: [
    //   { name: "pg-connections-grafana.png", kind: "image", size: "312 KB" },
    //   { name: "incident-2026-08-notes.pdf", kind: "pdf", size: "96 KB" },
    // ],
  },
  {
    type: "link",
    title: "Concatenated indexes, Use The Index, Luke",
    url: "https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys",
    desc: "Explains how column order in a multi-column index decides which queries can use it.",
    ctx: "Rule of thumb I keep forgetting: equality columns first, range column last. Applies to the (org_id, created_at) index on events.",
    folder: "data",
    tags: ["postgres", "performance", "tutorial"],
    savedAt: "2026-01-04",
    // meta: { author: "Markus Winand", len: "7 min read" },
  },
  {
    type: "link",
    title: "drizzle-team/drizzle-orm",
    url: "https://github.com/drizzle-team/drizzle-orm",
    desc: "TypeScript ORM with a SQL-like query builder and a companion migration tool, designed for serverless and edge runtimes.",
    ctx: "Compare with Prisma for the edge-runtime service. Check how drizzle-kit generates migrations and whether it works with our shadow database setup.",
    tags: ["typescript", "github"],
    savedAt: "2026-01-05",
    // meta: { author: "Drizzle Team", len: "Repository" },
  },
  {
    type: "link",
    title: "Generics, TypeScript Handbook",
    url: "https://www.typescriptlang.org/docs/handbook/2/generics.html",
    desc: "Introduction to generic types, generic constraints, and using type parameters in constraints.",
    ctx: "Refresher before writing the generic repository helper. The constraints section (K extends keyof T) is what I need.",
    folder: "learning",
    tags: ["typescript", "docs"],
    savedAt: "2026-01-06",
    // meta: { author: "TypeScript team", len: "10 min read" },
  },
  {
    type: "link",
    title: "Islands architecture",
    url: "https://www.patterns.dev/vanilla/islands-architecture/",
    desc: "Describes the islands pattern: render the page on the server and hydrate only the interactive regions.",
    ctx: "Useful mental model for the marketing site. Compare with RSC, since the goal is the same but the mechanism is different.",
    folder: "arch",
    tags: ["patterns", "performance"],
    savedAt: "2026-01-07",
    // meta: { author: "Lydia Hallie, Addy Osmani", len: "6 min read" },
  },
  {
    type: "link",
    title: "Strangler Fig Application",
    url: "https://martinfowler.com/bliki/StranglerFigApplication.html",
    desc: "Description of gradually replacing a legacy system by routing functionality to new services piece by piece.",
    ctx: "Bring to Thursday's architecture review. Frames the billing migration as incremental instead of a big-bang rewrite.",
    folder: "arch",
    tags: ["patterns", "migration"],
    fav: true,
    savedAt: "2026-01-08",
    // meta: { author: "Martin Fowler", len: "5 min read" },
  },
  {
    type: "link",
    title: "shadcn-ui/ui",
    url: "https://github.com/shadcn-ui/ui",
    desc: "Copy-and-own component collection built on Radix primitives and Tailwind, distributed through a CLI and a registry.",
    ctx: "Look at how the registry and CLI are structured, not just the components. Good reference for distributing our internal design system.",
    folder: "frontend",
    tags: ["react", "css", "github"],
    savedAt: "2026-01-09",
    // meta: { author: "shadcn", len: "Repository" },
  },
  {
    type: "link",
    title: "Best practices, Playwright",
    url: "https://playwright.dev/docs/best-practices",
    desc: "Guidance on writing resilient end-to-end tests: user-facing locators, test isolation, and avoiding third-party dependencies.",
    folder: "tooling",
    tags: ["testing", "docs"],
    savedAt: "2026-01-10",
    // meta: { author: "Playwright team", len: "8 min read" },
  },
  {
    type: "link",
    title: "Session strategies, Auth.js",
    url: "https://authjs.dev/concepts/session-strategies",
    desc: "Compares JWT and database session strategies and when each one fits.",
    tags: ["auth", "nextjs"],
    savedAt: "2026-01-11",
    // meta: { author: "Auth.js", len: "4 min read" },
  },
  {
    type: "link",
    title: "How Discord stores trillions of messages",
    url: "https://discord.com/blog/how-discord-stores-trillions-of-messages",
    desc: "Engineering write-up on migrating message storage to a new database and the partitioning problems that drove the move.",
    ctx: "Read for the hot-partition discussion. Relevant if we ever shard the events table.",
    folder: "arch",
    tags: ["scaling", "case-study"],
    savedAt: "2026-01-12",
    // meta: { author: "Discord engineering", len: "12 min read" },
  },
  {
    type: "snippet",
    title: "useDebouncedValue hook",
    desc: "Returns a value that only updates after the input has stopped changing for a given delay.",
    code: 'import { useEffect, useState } from "react";\n\nexport function useDebouncedValue<T>(value: T, delay = 250): T {\n  const [debounced, setDebounced] = useState(value);\n\n  useEffect(() => {\n    const id = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(id);\n  }, [value, delay]);\n\n  return debounced;\n}',
    ctx: "Cleaner than pulling in lodash just for the search box. 250ms felt right for the docs search.",
    folder: "frontend",
    tags: ["react", "typescript", "snippet"],
    savedAt: "2026-02-01",
    // meta: { len: "12 lines" },
  },
  {
    type: "chat",
    title: "Multi-tenant schema design in Postgres",
    desc: "Comparison of schema-per-tenant, shared schema with tenant_id, and row-level security, with a migration order for existing tables.",
    ctx: "Landed on a shared schema with row-level security. The final recommendation is near the end, along with the order for adding tenant_id to existing tables.",
    folder: "data",
    tags: ["postgres", "multitenancy"],
    fav: true,
    savedAt: "2026-03-01",
    // meta: { len: "22 messages" },
  },
  {
    type: "note",
    title: "Zero-downtime column rename checklist",
    desc: "Steps for renaming a column without breaking running application versions.",
    body: "1. Add the new column as nullable.\n2. Write to both columns from the application.\n3. Backfill existing rows in batches.\n4. Switch reads to the new column.\n5. Stop writing the old column.\n6. Drop the old column one release later.",
    ctx: "Worked for users.display_name. Backfill in batches of 5k with a short sleep or replication lag spikes.",
    folder: "data",
    tags: ["postgres", "migration"],
    savedAt: "2026-04-01",
    // meta: { len: "6 steps" },
  },
  {
    type: "link",
    title: "Bun 1.2",
    url: "https://bun.sh/blog/bun-v1.2",
    desc: "Release notes for Bun 1.2, including Node.js compatibility work and new built-in database and storage clients.",
    savedAt: "2026-05-01",
    tags: ["bun", "javascript", "runtime"],
    // meta: { author: "Bun", len: "11 min read" },
  },
  {
    type: "link",
    title: "Tailwind CSS v4.0",
    url: "https://tailwindcss.com/blog/tailwindcss-v4",
    desc: "Announcement of Tailwind CSS v4 with CSS-first configuration and a new high-performance engine.",
    ctx: "Check whether the config migration codemod handles our custom plugin.",
    tags: ["css"],
    savedAt: "2026-05-02",
    // meta: { author: "Tailwind Labs", len: "9 min read" },
  },
  {
    type: "link",
    title: "prisma/prisma-examples",
    url: "https://github.com/prisma/prisma-examples",
    desc: "Ready-to-run example projects using Prisma with Next.js, Express and other frameworks.",
    tags: ["prisma", "github"],
    savedAt: "2026-05-03",
    // meta: { author: "Prisma", len: "Repository" },
  },
  {
    type: "link",
    title: "Sunsetting Create React App",
    url: "https://react.dev/blog/2025/02/14/sunsetting-create-react-app",
    desc: "React team announcement that Create React App is being deprecated, and the recommended alternatives.",
    ctx: "Superseded. We are on Next.js now.",
    folder: "frontend",
    tags: ["react"],
    archived: true,
    savedAt: "5/2/2025",
    // meta: { author: "React team", len: "6 min read" },
  },
];
